{% set name = "falcon-multipart" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ae73fdddd94299f2cb181b8f1e8ab17d3ce182daabbb11ce862f0bd471a3d1d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - falcon >=0.3

test:
  imports:
    - falcon_multipart

about:
  home: https://github.com/yohanboniface/falcon-multipart
  license: MIT
  license_family: MIT
  summary: 'Parse multipart/form-data requests in Falcon'
  description: |
    falcon-multipart is a middleware for Falcon used to
    handle multipart/form-data requests.
  dev_url: https://github.com/yohanboniface/falcon-multipart

extra:
  recipe-maintainers:
    - blink1073
    - timkpaine

