{% set version = "0.16.3" %}

package:
  name: metakernel
  version: {{ version }}

source:
  fn: metakernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: bc59a5cb9289fc82621dccdc3f41830307c653405428aa23940a5ae5848054fc

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - pexpect >=4.2

  run:
    - python
    - jupyter
    - pexpect >=4.2

test:
  # Python imports
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD License
  summary: 'Metakernel for Jupyter'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
